In [57]:
import numpy as np
import pandas as pd

In [58]:
df = pd.read_csv("forestfires.csv")

In [59]:
df.head()

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [60]:
df1 = df.loc[:, "FFMC":"rain"]

In [61]:
df1.head()

FFMC   DMC     DC  ISI  temp  RH  wind  rain
0  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0
1  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0
2  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0
3  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2
4  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0

In [62]:
from sklearn.model_selection import train_test_split

In [63]:
# 70% train
# 30% test
X_train, X_test, y_train, y_test = train_test_split(df1, df["area"], train_size = 0.7 )

In [64]:
X_train

FFMC    DMC     DC   ISI  temp  RH  wind  rain
70   91.2   48.3   97.8  12.5  15.8  27   7.6   0.0
344  91.5  130.1  807.1   7.5  12.2  66   4.9   0.0
267  92.1  152.6  658.2  14.3  23.7  24   3.1   0.0
127  93.5  149.3  728.6   8.1  17.2  43   3.1   0.0
117  91.7   35.8   80.8   7.8  15.2  27   4.9   0.0
217  88.6   91.8  709.9   7.1  12.4  73   6.3   0.0
392  91.0  276.3  825.1   7.1  21.9  43   4.0   0.0
368  91.2   94.3  744.4   8.4  16.8  47   4.9   0.0
93   91.4  142.4  601.4  10.6  18.2  43   4.9   0.0
430  89.7  287.2  849.3   6.8  19.4  45   3.6   0.0
209  93.7   80.9  685.2  17.9  23.2  26   4.9   0.0
411  84.6    3.2   43.6   3.3   8.2  53   9.4   0.0
116  91.7   35.8   80.8   7.8  11.6  30   6.3   0.0
497  96.1  181.1  671.2  14.3  32.3  27   2.2   0.0
121  91.5  145.4  608.2  10.7  17.1  43   5.4   0.0
461  93.7  231.1  715.1   8.4  18.9  64   4.9   0.0
130  68.2   21.5   87.2   0.8  15.4  40   2.7   0.0
433  93.6  235.1  723.1  10.1  20.9  66   4.9   0.0
76   86.6   13.2   43.0   5.3  15.7  43   3.1   0.0
460  93.7  231.1  715.1   8.4  18.9  64   4.9   0.0
515  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0
105  85.9   19.5   57.3   2.8  12.7  52   6.3   0.0
459  91.6  273.8  819.1   7.7  15.5  72   8.0   0.0
439  91.1   91.3  738.1   7.2  19.1  46   2.2   0.0
414  93.6  235.1  723.1  10.1  24.1  50   4.0   0.0
512  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0
128  91.4   37.9  673.8   5.2  15.9  46   3.6   0.0
384  91.6  273.8  819.1   7.7  21.3  44   4.5   0.0
317  92.4   96.2  739.4   8.6  19.2  24   4.9   0.0
202  83.9    8.7   32.1   2.1   8.8  68   2.2   0.0
..    ...    ...    ...   ...   ...  ..   ...   ...
262  91.6  112.4  573.0   8.9  21.4  42   3.1   0.0
90   90.2   96.9  624.2   8.9  14.7  59   5.8   0.0
274  84.0   27.8  354.6   5.3   5.1  61   8.0   0.0
184  93.9  135.7  586.7  15.1  20.8  34   4.9   0.0
312  50.4   46.2  706.6   0.4  12.2  78   6.3   0.0
118  90.1   39.7   86.6   6.2  10.6  30   4.0   0.0
114  88.1   25.7   67.6   3.8  15.8  27   7.6   0.0
354  92.1   99.0  745.3   9.6  18.7  50   2.2   0.0
331  91.2  124.4  795.3   8.5  21.5  28   4.5   0.0
87   92.9  137.0  706.4   9.2  22.4  34   2.2   0.0
222  87.6   52.2  103.8   5.0  11.0  46   5.8   0.0
342  91.5  130.1  807.1   7.5  20.6  37   1.8   0.0
503  94.5  139.4  689.1  20.0  29.2  30   4.9   0.0
71   94.3   85.1  692.3  15.9  17.7  37   3.6   0.0
340  91.6  108.4  764.0   6.2  19.3  44   2.2   0.0
359  92.5  122.0  789.7  10.2  21.1  39   2.2   0.0
405  94.6  212.1  680.9   9.5  27.9  27   2.2   0.0
29   93.5  149.3  728.6   8.1  22.8  39   3.6   0.0
107  90.2   99.6  631.2   6.3  21.4  33   3.1   0.0
74   93.3  141.2  713.9  13.9  27.6  30   1.3   0.0
513  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0
281  85.4   25.4  349.7   2.6   5.1  24   8.5   0.0
391  91.1   91.3  738.1   7.2  20.7  46   2.7   0.0
292  91.6  100.2  466.3   6.3  22.9  40   1.3   0.0
193  92.9  133.3  699.6   9.2  24.3  25   4.0   0.0
297  90.4   89.5  290.8   6.4  15.4  45   2.2   0.0
382  95.2  217.7  690.0  18.0  28.2  29   1.8   0.0
226  91.7   48.5  696.1  11.1  16.1  44   4.0   0.0
406  87.1  291.3  860.6   4.0  17.0  67   4.9   0.0
14   92.9  133.3  699.6   9.2  26.4  21   4.5   0.0

[361 rows x 8 columns]

# 两个方法
**StandardScaler**

**MinMaxScaler**

In [65]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

In [66]:
ss.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [67]:
X_train_ss = ss.transform(X_train)
X_test_ss = ss.transform(X_test)

In [68]:
X_test_ss.shape # array

(156, 8)

In [69]:
X_test_ss.mean(axis = 0)

array([-0.24203385, -0.20227088, -0.23428041, -0.0088161 , -0.2893274 ,
        0.26441484, -0.03204439, -0.02618091])

In [70]:
from sklearn.preprocessing import MinMaxScaler

In [71]:
mms = MinMaxScaler((0,2))

In [72]:
mms.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 2))

In [73]:
mms.transform(X_train)

array([[ 1.78165939,  0.31775701,  0.19476985, ...,  0.30379747,
         1.6       ,  0.        ],
       [ 1.79475983,  0.88404292,  1.87338776, ...,  1.29113924,
         1.        ,  0.        ],
       [ 1.8209607 ,  1.03980616,  1.52100343, ...,  0.2278481 ,
         0.6       ,  0.        ],
       ..., 
       [ 1.80349345,  0.31914157,  1.61069696, ...,  0.73417722,
         0.8       ,  0.        ],
       [ 1.60262009,  2.        ,  2.        , ...,  1.3164557 ,
         1.        ,  0.        ],
       [ 1.8558952 ,  0.90619592,  1.61898   , ...,  0.15189873,
         0.91111111,  0.        ]])

# Normalization

什么时候用到normalizatoin？

样本与样本间距离的计算，比如聚类，kNN,文本分类（词之间的距离）。对于这些场景，你就要保证所有的数据是在一个合理的量纲之内。在这样的场景下才需要对样本做normalization

这里的nornalization是把样本变为unit norm（正则项）。

这里有两个
一个是函数normalize,一个是class mormalizer

In [ ]:
sklearn.preprocessing.normalize(X, norm='l2', axis=1, copy=True, return_norm=False)

class sklearn.preprocessing.Normalizer(norm='l2', copy=True)

class里的normalizer有transform，但是这里的transform没什么实际意义，因为normalizer是对每一个sample作用的，而不是feature。而之所以开发这个class版的normalizer，是为了之后的pipline。

我们假设样本间是独立的，既然是独立的transform就无意义，没必要让训练集和测试集按上面标准化那样，只用train的mean和std。所以想怎样就怎样，因为normalizer每次值针对一条样本。

In [75]:
from sklearn.preprocessing import Normalizer
norm = Normalizer()

In [76]:
norm.fit(X_train)

Normalizer(copy=True, norm='l2')

In [77]:
norm.transform(X_train)

array([[ 0.62331649,  0.33011169,  0.66842492, ...,  0.18453449,
         0.05194304,  0.        ],
       [ 0.11085464,  0.15761955,  0.97782275, ...,  0.07996073,
         0.00593648,  0.        ],
       [ 0.13486662,  0.22345979,  0.96383507, ...,  0.0351444 ,
         0.00453948,  0.        ],
       ..., 
       [ 0.12998912,  0.06875106,  0.9867549 , ...,  0.0623721 ,
         0.00567019,  0.        ],
       [ 0.09515333,  0.31823383,  0.94017175, ...,  0.07319487,
         0.00535306,  0.        ],
       [ 0.12919208,  0.18537464,  0.97290394, ...,  0.02920381,
         0.00625796,  0.        ]])

# 2.2 Binarization

In [78]:
df["DC"].mean()

547.9400386847191

In [79]:
from sklearn.preprocessing import Binarizer
bi = Binarizer(548)

In [80]:
DC_bi = bi.fit_transform(df["DC"])

/Users/xu/anaconda/envs/py35/lib/python3.5/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/xu/anaconda/envs/py35/lib/python3.5/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [81]:
DC_bi.shape

(1, 517)

这样是放不到元数据里的，我们希望是1列，有517行

In [82]:
df['DC_bi'] = DC_bi[0, :]

In [83]:
df.head()

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  DC_bi
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0    0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0    1.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0    1.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0    0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0    0.0

In [84]:
help(pd.cut)
# bins 是 分为多少个区间

Help on function cut in module pandas.tools.tile:

cut(x, bins, right=True, labels=None, retbins=False, precision=3, include_lowest=False)
    Return indices of half-open bins to which each value of `x` belongs.
    
    Parameters
    ----------
    x : array-like
        Input array to be binned. It has to be 1-dimensional.
    bins : int or sequence of scalars
        If `bins` is an int, it defines the number of equal-width bins in the
        range of `x`. However, in this case, the range of `x` is extended
        by .1% on each side to include the min or max values of `x`. If
        `bins` is a sequence it defines the bin edges allowing for
        non-uniform bin width. No extension of the range of `x` is done in
        this case.
    right : bool, optional
        Indicates whether the bins include the rightmost edge or not. If
        right == True (the default), then the bins [1,2,3,4] indicate
        (1,2], (2,3], (3,4].
    labels : array or boolean, default None
      

In [85]:
pd.cut(df['DC'], 5)
# df['DC']这一列上的每一个值对应所属于的区间
# 但我们该选择哪个作为阈值呢

0      (7.0473, 178.44]
1      (519.52, 690.06]
2      (519.52, 690.06]
3      (7.0473, 178.44]
4      (7.0473, 178.44]
5      (348.98, 519.52]
6      (348.98, 519.52]
7      (519.52, 690.06]
8       (690.06, 860.6]
9       (690.06, 860.6]
10      (690.06, 860.6]
11      (690.06, 860.6]
12     (519.52, 690.06]
13     (519.52, 690.06]
14      (690.06, 860.6]
15      (690.06, 860.6]
16     (7.0473, 178.44]
17     (519.52, 690.06]
18     (7.0473, 178.44]
19     (7.0473, 178.44]
20      (690.06, 860.6]
21      (690.06, 860.6]
22     (178.44, 348.98]
23     (519.52, 690.06]
24     (519.52, 690.06]
25     (519.52, 690.06]
26     (519.52, 690.06]
27     (519.52, 690.06]
28      (690.06, 860.6]
29      (690.06, 860.6]
             ...       
487    (519.52, 690.06]
488    (519.52, 690.06]
489    (519.52, 690.06]
490    (519.52, 690.06]
491    (519.52, 690.06]
492    (519.52, 690.06]
493    (519.52, 690.06]
494    (519.52, 690.06]
495    (519.52, 690.06]
496    (519.52, 690.06]
497    (519.52, 

## 但我们该选择哪个作为阈值呢
一种是随机，把bins设为5，6，7. 更多情况是根据业务来划分的。比如你认为你的而客户可以分为五种不同价值的客户。

但是cut后的结果是string,不是数字，我们用通过一种方式来把这个变为数字。于是引出了encoding.


## OneHotEncoder

sklearn.preprocessing.OneHotEncoder这个不好用，经常报错
这里我们推荐用pandas的get_dummies

In [86]:
pd.get_dummies(data=df, columns=['month', 'day', 'DC_bi'])

X  Y  FFMC    DMC     DC   ISI  temp  RH  wind  rain    ...      \
0    7  5  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0    ...       
1    7  4  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0    ...       
2    7  4  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0    ...       
3    8  6  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2    ...       
4    8  6  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0    ...       
5    8  6  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0    ...       
6    8  6  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0    ...       
7    8  6  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0    ...       
8    8  6  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0    ...       
9    7  5  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0    ...       
10   7  5  92.5   88.0  698.6   7.1  17.8  51   7.2   0.0    ...       
11   7  5  92.8   73.2  713.0  22.6  19.3  38   4.0   0.0    ...       
12   6  5  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0    ...       
13   6  5  90.9  126.5  686.5   7.0  21.3  42   2.2   0.0    ...       
14   6  5  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0    ...       
15   6  5  93.3  141.2  713.9  13.9  22.9  44   5.4   0.0    ...       
16   5  5  91.7   35.8   80.8   7.8  15.1  27   5.4   0.0    ...       
17   8  5  84.9   32.8  664.2   3.0  16.7  47   4.9   0.0    ...       
18   6  4  89.2   27.9   70.8   6.3  15.9  35   4.0   0.0    ...       
19   6  4  86.3   27.4   97.1   5.1   9.3  44   4.5   0.0    ...       
20   6  4  91.0  129.5  692.6   7.0  18.3  40   2.7   0.0    ...       
21   5  4  91.8   78.5  724.3   9.2  19.1  38   2.7   0.0    ...       
22   7  4  94.3   96.3  200.0  56.1  21.0  44   4.5   0.0    ...       
23   7  4  90.2  110.9  537.4   6.2  19.5  43   5.8   0.0    ...       
24   7  4  93.5  139.4  594.2  20.3  23.7  32   5.8   0.0    ...       
25   7  4  91.4  142.4  601.4  10.6  16.3  60   5.4   0.0    ...       
26   7  4  92.4  117.9  668.0  12.2  19.0  34   5.8   0.0    ...       
27   7  4  90.9  126.5  686.5   7.0  19.4  48   1.3   0.0    ...       
28   6  3  93.4  145.4  721.4   8.1  30.2  24   2.7   0.0    ...       
29   6  3  93.5  149.3  728.6   8.1  22.8  39   3.6   0.0    ...       
..  .. ..   ...    ...    ...   ...   ...  ..   ...   ...    ...       
487  5  4  95.1  141.3  605.8  17.7  26.4  34   3.6   0.0    ...       
488  4  4  95.1  141.3  605.8  17.7  19.4  71   7.6   0.0    ...       
489  4  4  95.1  141.3  605.8  17.7  20.6  58   1.3   0.0    ...       
490  4  4  95.1  141.3  605.8  17.7  28.7  33   4.0   0.0    ...       
491  4  4  95.8  152.0  624.1  13.8  32.4  21   4.5   0.0    ...       
492  1  3  95.9  158.0  633.6  11.3  32.4  27   2.2   0.0    ...       
493  1  3  95.9  158.0  633.6  11.3  27.5  29   4.5   0.0    ...       
494  6  6  96.0  164.0  643.0  14.0  30.8  30   4.9   0.0    ...       
495  6  6  96.2  175.5  661.8  16.8  23.9  42   2.2   0.0    ...       
496  4  5  96.2  175.5  661.8  16.8  32.6  26   3.1   0.0    ...       
497  3  4  96.1  181.1  671.2  14.3  32.3  27   2.2   0.0    ...       
498  6  5  96.1  181.1  671.2  14.3  33.3  26   2.7   0.0    ...       
499  7  5  96.1  181.1  671.2  14.3  27.3  63   4.9   6.4    ...       
500  8  6  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8    ...       
501  7  5  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8    ...       
502  4  4  96.1  181.1  671.2  14.3  20.7  69   4.9   0.4    ...       
503  2  4  94.5  139.4  689.1  20.0  29.2  30   4.9   0.0    ...       
504  4  3  94.5  139.4  689.1  20.0  28.9  29   4.9   0.0    ...       
505  1  2  91.0  163.2  744.4  10.1  26.7  35   1.8   0.0    ...       
506  1  2  91.0  166.9  752.6   7.1  18.5  73   8.5   0.0    ...       
507  2  4  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0    ...       
508  1  2  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0    ...       
509  5  4  91.0  166.9  752.6   7.1  21.1  71   7.6   1.4    ...       
510  6  5  91.0  166.9  752.6   7.1  18.2  62

# sklearn 里的所有模型绝不接受missing value

但是删除missing value 不是一个好办法，最好用别的数字来替换它。

sklean里有一个impiter的方法，有三种替换missing value的方法。

`class sklearn.preprocessing.Imputer(missing_values='NaN', strategy='mean', axis=0, verbose=0, copy=True)`


1. mean 平均数. 一般来说我们用一列的平均数来代替,令axis=0即可。而不是一行的平均数来代替。strategy选择'mean'
2. median 中位数
3. most_frequent 众数

In [87]:
df.loc[df['DC'] >= 600, 'DC_na'] = np.nan
# 否则“DC”不变, 但是下面这种写法我不理解
# 为什么这么写呢，即使不写否则也可以吧
df.loc[df['DC'] >= 600, 'DC_na'] = df['DC']

In [88]:
from sklearn.preprocessing import Imputer
im = Imputer()

In [89]:
df.head()

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  DC_bi  \
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0    0.0   
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0    1.0   
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0    1.0   
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0    0.0   
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0    0.0   

   DC_na  
0    NaN  
1  669.1  
2  686.9  
3    NaN  
4    NaN

In [90]:
im.fit_transform(df['DC'])

/Users/xu/anaconda/envs/py35/lib/python3.5/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/xu/anaconda/envs/py35/lib/python3.5/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([[  94.3,  669.1,  686.9,   77.5,  102.2,  488. ,  495.6,  608.2,
         692.6,  698.6,  698.6,  713. ,  665.3,  686.5,  699.6,  713.9,
          80.8,  664.2,   70.8,   97.1,  692.6,  724.3,  200. ,  537.4,
         594.2,  601.4,  668. ,  686.5,  721.4,  728.6,  692.3,  709.9,
         706.8,  718.3,  724.3,  730.2,  669.1,  682.6,  686.9,   67.6,
         366.7,  624.2,  647.1,  698.6,  735.7,  692.3,  686.5,  442.9,
          64.7,  103.8,  706.4,  631.2,  654.1,  654.1,  661.3,  706.4,
         730.2,  691.8,   34. ,   43. ,  102.2,  102.2,  466.6,  631.2,
         638.8,  661.3,  668. ,  668. ,  668. ,   77.5,   97.8,  692.3,
          77.5,  614.5,  713.9,   26.6,   43. ,  103.8,  529.8,  561.6,
         601.4,  631.2,  647.1,  654.1,  661.3,  706.4,  706.4,  706.4,
         728.6,   80.8,  624.2,   80.8,  488. ,  601.4,  638.8,  704.4,
          30.2,   15.5,  601.4,  601.4,  601.4,  614.5,  647.1,  674.4,
           9.3,   57.3,   74.3,  631.2,  698.6,  709.9,   57.3, 

## 但是设成mean，medien这样的值并没有什么意义

比如titannic的比赛里，对于性别失值，我们可以通过名字来猜测。对于年龄的缺失值，我们可以通过miss, mrs这样的称呼来推测。 而不只是简单得用一个平均数去代替。

实在不知道就填一些没有意义的值。-999，-1之类的。对模型没什么大的影响。
而xgboost里就是用这种non sence的值，比如-999.


如果还有很多的无穷大和无穷小，我们先用nan来替换掉这些

In [ ]:
df.replace(np.inf, np.nan)

In [ ]:
df.fillna(-999)

# 2.3 feature selection
`class sklearn.feature_selection.SelectFromModel(estimator, threshold=None, prefit=False)`



In [95]:
from sklearn.feature_selection import SelectFromModel

In [99]:
modelData = pd.get_dummies(data=df, columns=['month', 'day', 'DC_bi'])
modelData.head()

X  Y  FFMC   DMC     DC  ISI  temp  RH  wind  rain    ...      month_sep  \
0  7  5  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0    ...            0.0   
1  7  4  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0    ...            0.0   
2  7  4  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0    ...            0.0   
3  8  6  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2    ...            0.0   
4  8  6  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0    ...            0.0   

   day_fri  day_mon  day_sat  day_sun  day_thu  day_tue  day_wed  DC_bi_0.0  \
0      1.0      0.0      0.0      0.0      0.0      0.0      0.0        1.0   
1      0.0      0.0      0.0      0.0      0.0      1.0      0.0        0.0   
2      0.0      0.0      1.0      0.0      0.0      0.0      0.0        0.0   
3      1.0      0.0      0.0      0.0      0.0      0.0      0.0        1.0   
4      0.0      0.0      0.0      1.0      0.0      0.0      0.0        1.0   

   DC_bi_1.0  
0        0.0  
1        1.0  
2        1.0  
3        0.0  
4        0.0  

[5 rows x 33 columns]

In [102]:
# 先剔除掉目标变量
# 0 for rows and 1 for columns.
# 如果是在modelData上直接删除的话，令inplace=True
xdata = modelData.drop('area', axis = 1)
ydata = modelData['area']

In [98]:
xdata.head()

X  Y  FFMC   DMC     DC  ISI  temp  RH  wind  rain    ...      month_sep  \
0  7  5  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0    ...            0.0   
1  7  4  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0    ...            0.0   
2  7  4  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0    ...            0.0   
3  8  6  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2    ...            0.0   
4  8  6  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0    ...            0.0   

   day_fri  day_mon  day_sat  day_sun  day_thu  day_tue  day_wed  DC_bi_0.0  \
0      1.0      0.0      0.0      0.0      0.0      0.0      0.0        1.0   
1      0.0      0.0      0.0      0.0      0.0      1.0      0.0        0.0   
2      0.0      0.0      1.0      0.0      0.0      0.0      0.0        0.0   
3      1.0      0.0      0.0      0.0      0.0      0.0      0.0        1.0   
4      0.0      0.0      0.0      1.0      0.0      0.0      0.0        1.0   

   DC_bi_1.0  
0        0.0  
1        1.0  
2        1.0  
3        0.0  
4        0.0  

[5 rows x 32 columns]

##  L1-based feature selection

In [103]:
from sklearn.linear_model import Lasso
lasso = Lasso()
lasso.fit(xdata.fillna(-999), ydata)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [105]:
lasso.coef_

array([  1.88324733e+00,   9.58928425e-02,  -1.25434649e-02,
         8.75375954e-02,  -2.88298355e-02,  -4.81990096e-01,
         7.97824030e-01,  -2.21426241e-01,   1.41927224e+00,
        -0.00000000e+00,   6.52084401e-03,   0.00000000e+00,
        -0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,  -0.00000000e+00,
        -0.00000000e+00,   0.00000000e+00,  -0.00000000e+00,
        -0.00000000e+00,   4.03266456e+00,  -0.00000000e+00,
        -0.00000000e+00,   7.53637559e+00,  -0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,  -0.00000000e+00,
         0.00000000e+00,  -0.00000000e+00])

从上面的结果我们能够看到每个feature对应的系数，而那些系数为0的feature说明不重要，我们可以删掉。这里要注意一点，**不要删掉OneHotEncoder**的feature。这样的feature使我们认为做得，而且大部分为0.如果删了的话，你就把month,day全部删掉了。

只要是L1的模型，都可以做这样的操作。

当然，人工可以删没有用的feature。但我们也可以直接用sklearn来自动删除。
其实解释把模型和评估的方式一起传入。

SelectFromModel is a meta-transformer that can be used along with any estimator that has a coef_ or feature_importances_ attribute after fitting. The features are considered unimportant and removed, if the corresponding coef_ or feature_importances_ values are below the provided threshold parameter. Apart from specifying the threshold numerically, there are built-in heuristics for finding a threshold using a string argument. 

In [106]:
# 直接传模型
model = SelectFromModel(lasso)

In [ ]:
# 这里transform没什么意义，为了pipeline
xdata.replace(np.inf, np.nan)
xdata.fillna(-999)
model.fit_transform(xdata)

 ## Tree-based feature selection

In [110]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()

In [111]:
rf.fit(xdata.fillna(-999), ydata)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)

In [112]:
rf.feature_importances_

array([  6.11847175e-02,   5.34006108e-02,   1.62500816e-02,
         8.63070163e-02,   3.46538478e-02,   1.26294636e-01,
         4.68379150e-01,   5.70187219e-02,   2.56301839e-02,
         3.11604090e-06,   3.64379170e-02,   1.52402704e-06,
         2.42264197e-04,   1.82006269e-05,   8.27505764e-05,
         0.00000000e+00,   9.98202242e-04,   2.21117792e-06,
         1.40607924e-05,   2.07701569e-04,   0.00000000e+00,
         1.36117636e-05,   8.24621456e-03,   4.99296895e-04,
         6.31038969e-04,   8.21554623e-03,   6.55483520e-03,
         2.73605186e-03,   2.52492634e-03,   8.47749408e-04,
         6.13309424e-05,   2.54248369e-03])

In [119]:
model = SelectFromModel(rf, prefit=True)
print (xdata.shape)
xdata.fillna(-999, inplace=True)
xdata_new = model.transform(xdata)
print (xdata_new.shape)

(517, 32)
(517, 8)


In [121]:
xdata_new

array([[   7. ,    5. ,   26.2, ...,    8.2,   51. , -999. ],
       [   7. ,    4. ,   35.4, ...,   18. ,   33. ,  669.1],
       [   7. ,    4. ,   43.7, ...,   14.6,   33. ,  686.9],
       ..., 
       [   7. ,    4. ,   56.7, ...,   21.2,   70. ,  665.6],
       [   1. ,    4. ,  146. , ...,   25.6,   42. ,  614.7],
       [   6. ,    3. ,    3. , ...,   11.8,   31. , -999. ]])

# 2.4 根据score选择feature

In [123]:
from sklearn.feature_selection import VarianceThreshold, SelectKBest, SelectPercentile
v = VarianceThreshold(0.5)

In [124]:
v.fit_transform(modelData.fillna(-999)).shape

(517, 11)

In [125]:
modelData.shape

(517, 33)

In [126]:
modelData.dtypes

X              int64
Y              int64
FFMC         float64
DMC          float64
DC           float64
ISI          float64
temp         float64
RH             int64
wind         float64
rain         float64
area         float64
DC_na        float64
month_apr    float64
month_aug    float64
month_dec    float64
month_feb    float64
month_jan    float64
month_jul    float64
month_jun    float64
month_mar    float64
month_may    float64
month_nov    float64
month_oct    float64
month_sep    float64
day_fri      float64
day_mon      float64
day_sat      float64
day_sun      float64
day_thu      float64
day_tue      float64
day_wed      float64
DC_bi_0.0    float64
DC_bi_1.0    float64
dtype: object

In [137]:
Xdata = modelData.drop('area', axis=1)
Ydata = modelData['area']
Xdata.fillna(-999, inplace=True)

In [141]:
from sklearn.feature_selection import f_regression
skb = SelectKBest(f_regression, k=20)

In [143]:
skb.fit_transform(Xdata, Ydata).shape

(517, 20)

## 总结
从实用性的角度来讲，我们最常用的还是feature importance, 就是tree based，很少用单个变量。
优先考虑 tree based, 然后是L1 based, 最后考虑一些小功能。

# 降维方法：PCA VS TSVD

PCA应用最多的地方实在图像的压缩上.
这两个算法的区别在于：
1. PCA要计算协方差矩阵（covariance matrix)
2. TSVD不需要计算协方差矩阵

In [144]:
from sklearn.decomposition import PCA, TruncatedSVD
pca = PCA(20)

In [146]:
# 先做标准化，在做pca. 因为涉及到了矩阵计算，协方差的计算，量纲不一致，肯定有问题
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

In [149]:
pca.fit_transform(ss.fit_transform(Xdata)).shape

(517, 20)

In [154]:
np.sum(pca.explained_variance_ratio_)
# 说明我们选取的20个主要成分能解释91.6%的方差，能解释92%的数据变动

0.91608489936100235

## TSVD

In [155]:
tsvd = TruncatedSVD(20)

In [156]:
tsvd.fit_transform(ss.fit_transform(Xdata))

array([[ 4.64706667,  0.06996523, -0.25495601, ...,  0.60030415,
         0.02088443,  0.17479408],
       [-0.73013911,  1.25319739, -0.86318051, ..., -0.27387011,
        -1.37078476,  0.29622245],
       [-0.49556172,  1.45281448, -1.00201551, ...,  0.44010001,
        -0.29056734,  1.61407777],
       ..., 
       [-0.23265865,  1.16085204,  2.85403856, ..., -0.12380147,
         0.29274955, -0.03260624],
       [-1.8519848 , -1.06715914,  0.28917776, ...,  0.44686956,
         0.21878406, -0.09024007],
       [ 4.54267777,  1.36243988, -0.39384144, ...,  8.11182608,
         4.6570511 ,  5.91759521]])